// <auto-generated />
using System;
using APIGastroLink.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIGastroLink.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250930132841_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIGastroLink.Models.CategoriaPrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CTP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CTP_CATEGORIA");

                    b.HasKey("Id");

                    b.ToTable("CATEGORIAS_PRATOS");
                });

            modelBuilder.Entity("APIGastroLink.Models.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FPG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FPG_FORMA");

                    b.HasKey("Id");

                    b.ToTable("FORMAS_PAGAMENTO");
                });

            modelBuilder.Entity("APIGastroLink.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ITP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITP_OBSERVACOES");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("ITP_PED_ID");

                    b.Property<int>("PratoId")
                        .HasColumnType("int")
                        .HasColumnName("ITP_PRA_ID");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("ITP_QUANTIDADE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITP_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PratoId");

                    b.ToTable("ITENS_PEDIDO");
                });

            modelBuilder.Entity("APIGastroLink.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LPD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LPD_ACAO");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("LPD_DATA_HORA");

                    b.Property<int>("MesaId")
                        .HasColumnType("int")
                        .HasColumnName("LPD_MSA_ID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("LPD_USU_ID");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LOG_PEDIDOS");
                });

            modelBuilder.Entity("APIGastroLink.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MSA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MSA_NUMERO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MSA_STATUS");

                    b.HasKey("Id");

                    b.ToTable("MESAS");
                });

            modelBuilder.Entity("APIGastroLink.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAG_DATA_PAGAMENTO");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAG_DESCONTO");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int")
                        .HasColumnName("PAG_FPG_ID");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("PAG_PED_ID");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAG_VALOR_PAGO");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PAGAMENTOS");
                });

            modelBuilder.Entity("APIGastroLink.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PED_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("PED_DATA_HORA");

                    b.Property<int>("MesaId")
                        .HasColumnType("int")
                        .HasColumnName("PED_MSA_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PED_STATUS");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("PED_USU_ID");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PED_VALOR_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PEDIDOS");
                });

            modelBuilder.Entity("APIGastroLink.Models.Prato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPratoId")
                        .HasColumnType("int")
                        .HasColumnName("PRA_CTP_ID");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRA_DESCRICAO");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit")
                        .HasColumnName("PRA_DISPONIVEL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRA_NOME");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRA_PRECO");

                    b.Property<double>("TempoMedioPreparo")
                        .HasColumnType("float")
                        .HasColumnName("PRA_TEMPO_MEDIO_PREPARO");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPratoId");

                    b.ToTable("PRATOS");
                });

            modelBuilder.Entity("APIGastroLink.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TPU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TPU_TIPO");

                    b.HasKey("Id");

                    b.ToTable("TIPOS_USUARIOS");
                });

            modelBuilder.Entity("APIGastroLink.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("USU_ATIVO");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USU_CPF");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USU_NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USU_SENHA");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("USU_TPU_ID");

                    b.HasKey("Id");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("APIGastroLink.Models.ItemPedido", b =>
                {
                    b.HasOne("APIGastroLink.Models.Pedido", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIGastroLink.Models.Prato", "Prato")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("APIGastroLink.Models.Log", b =>
                {
                    b.HasOne("APIGastroLink.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIGastroLink.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("APIGastroLink.Models.Pagamento", b =>
                {
                    b.HasOne("APIGastroLink.Models.FormaPagamento", "FormaPagamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIGastroLink.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPagamento");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("APIGastroLink.Models.Pedido", b =>
                {
                    b.HasOne("APIGastroLink.Models.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIGastroLink.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("APIGastroLink.Models.Prato", b =>
                {
                    b.HasOne("APIGastroLink.Models.CategoriaPrato", "CategoriaPrato")
                        .WithMany("Pratos")
                        .HasForeignKey("CategoriaPratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPrato");
                });

            modelBuilder.Entity("APIGastroLink.Models.Usuario", b =>
                {
                    b.HasOne("APIGastroLink.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("APIGastroLink.Models.CategoriaPrato", b =>
                {
                    b.Navigation("Pratos");
                });

            modelBuilder.Entity("APIGastroLink.Models.FormaPagamento", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("APIGastroLink.Models.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("APIGastroLink.Models.Pedido", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("APIGastroLink.Models.Prato", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("APIGastroLink.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
