INSERT INTO TIPOS_USUARIOS(TPU_TIPO) VALUES('GARÇOM');
INSERT INTO TIPOS_USUARIOS(TPU_TIPO) VALUES('CAIXA');
INSERT INTO TIPOS_USUARIOS(TPU_TIPO) VALUES('COZINHEIRO');

INSERT INTO FORMAS_PAGAMENTO(FPG_FORMA) VALUES('CARTÃO CRÉDITO');
INSERT INTO FORMAS_PAGAMENTO(FPG_FORMA) VALUES('CARTÃO DÉBITO');
INSERT INTO FORMAS_PAGAMENTO(FPG_FORMA) VALUES('PIX');
INSERT INTO FORMAS_PAGAMENTO(FPG_FORMA) VALUES('DINHEIRO');

INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Entradas');
INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Pratos Principais');
INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Sobremesas');
INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Bebidas');
INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Aperitivos');

INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('1', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('2', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('3', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('4', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('5', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('6', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('7', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('8', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('9', 'LIVRE');
INSERT INTO MESAS(MSA_NUMERO, MSA_STATUS) VALUES ('10', 'LIVRE');