INSERT INTO TIPOS_USUARIOS(TPU_TIPO) VALUES('GARÇOM');
INSERT INTO TIPOS_USUARIOS(TPU_TIPO) VALUES('CAIXA');
INSERT INTO TIPOS_USUARIOS(TPU_TIPO) VALUES('COZINHEIRO');

INSERT INTO FORMAS_PAGAMENTO(FPG_FORMA) VALUES('CARTÃO CRÉDITO');
INSERT INTO FORMAS_PAGAMENTO(FPG_FORMA) VALUES('CARTÃO DÉBITO');
INSERT INTO FORMAS_PAGAMENTO(FPG_FORMA) VALUES('PIX');
INSERT INTO FORMAS_PAGAMENTO(FPG_FORMA) VALUES('DINHEIRO');

INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Entradas');
INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Pratos Principais');
INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Sobremesas');
INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Bebidas');
INSERT INTO CATEGORIAS_PRATOS (CTP_CATEGORIA) VALUES ('Aperitivos');
