CREATE PROCEDURE PROC_EXCLUSAO_LOGICA_USUARIO
	@ID_USUARIO INT
AS
BEGIN
	UPDATE USUARIOS
	SET USU_ATIVO = 0
	WHERE USU_ID = @ID_USUARIO
END;
GO

CREATE PROCEDURE PROC_INSERIR_PAGAMENTO
	@VALOR_PAGO INT,
	@DESCONTO INT,
	@DATA DATETIME,
	@FORMA_PAGAMENTO_ID  INT,
	@PEDIDO_ID INT
AS 
BEGIN
	INSERT INTO PAGAMENTOS (PAG_VALOR_PAGO, PAG_DESCONTO, PAG_DATA_PAGAMENTO, PAG_FPG_ID, PAG_PED_ID) 
	VALUES (@VALOR_PAGO, @DESCONTO, @DATA, @FORMA_PAGAMENTO_ID, @PEDIDO_ID);

	UPDATE PEDIDOS SET PED_STATUS = 'PAGO' WHERE PED_ID = @PEDIDO_ID;
END
GO