CREATE VIEW VW_PEDIDOS_COMPLETO AS
SELECT * FROM PEDIDOS 
JOIN ITENS_PEDIDO ON ITP_PED_ID = PED_ID
JOIN PRATOS ON PRA_ID = ITP_PRA_ID
JOIN MESAS ON MSA_ID = PED_MSA_ID
JOIN USUARIOS ON PED_USU_ID = USU_ID